version: '3.8'

services:
  nexus3:
    platform: linux/amd64
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - ./nexus-data:/nexus-data/sonatype/nexus3
      - ./deploy:/opt/sonatype/nexus/deploy
    working_dir: /opt/sonatype/nexus/
